SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `ofertes`;

CREATE TABLE `ofertes` (
  `idOferta` int(4) NOT NULL,
  `nom` varchar(200) NOT NULL,
  `descripcio` varchar(1000) NOT NULL,
  `preu` decimal(10,2) NOT NULL,
  `numFavorits` int(4) DEFAULT 0,
  `dataFinal` datetime NOT NULL,
  `idPais` char(2) DEFAULT 'ES',
  `imatges` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT INTO `ofertes` (`idOferta`, `nom`, `descripcio`, `preu`, `numFavorits`, `dataFinal`, `idPais`, `imatges`) VALUES
(41, 'Cambodja i Vietnam: 14 nits, vols, visites i trasllats', 'Eixida des de MADRID a l\'abril, maig i agost.\r\nInclou: 14 nits (2 nits en vol) + vol anada i tornada de Madrid - Cambodja - Vietnam (escala a Hong Kong) + 1 nit a Phom Penh + 2 nits a Siem Reap + 2 nits a Ho Chi Minh + 1 nit a Hue + 2 nits a Hoi An + 3 nits a Hanoi + 1 nit en creuer per la Badia de Halong (nit a bord del vaixell) + 12 esmorzars, 7 àpats, 1 brunch per persona (begudes no incloses als dinars i sopars) + guia de parla hispana + trasllats amb vehicle privat grupal + taxes d\'aeroport + assegurança bàsica de viatge + entrades per a les visites.', '2249.00', 0, '2025-01-01 19:34:00', 'VN', 'panoramica5 (1).jpg'),
(42, 'Especial Nadal i cap d\'any en un hotel 4* a Matalascañas (Costa de la Luz)', '2 días y 1 noche en hotel Moon Dreams El Cortijo en Matalascañas (Huelva) con desayunos. Niños de 0 a 11 años: viajan con un 50% de descuento. ¡Incluye Navidades y Fin de Año con cena especial!', '21.00', 0, '2025-01-08 19:38:00', 'ES', 'panoramica5.jpg'),
(43, 'Vacances a Sardenya a hotel 4* en pensió completa amb begudes i vaixell inclòs Primer nen al 70%!', 'EMBARCA EL TEU COTXE GRATIS!\r\n5 nits (1 nit d\'anada + 4 nits a l\'allotjament) + anada amb vaixell des de Barcelona en cabina interior i tornada en passatge bàsic amb la companyia Grimaldi Lines, allotjats a l\'Amareclub Red Sun 4* ubicat a Isola Rossa, amb pensió completa amb begudes + taxes d\'embarcament incloses + embarca el teu cotxe o moto gratis al vaixell. El preu està calculat amb base en 2 persones, si sou 4 persones, podeu viatjar des de 285€ per persona!', '349.00', 0, '2025-01-31 19:40:00', 'IT', 'panoramica5 (2).jpg'),
(44, 'Allotja\'t en un xalet de muntanya a Andorra, 1er nen GRATIS!', '3 dies i 2 nits a l\'Abba Ordino Babot Hotel 3* situat a Ordino (Andorra) al bell mig de la natura amb esmorzars + beguda de benvinguda + 1 accés a l\'spa de l\'hotel per persona i reserva + transfer diari a les pistes d\'esquí durant hivern de l\'1/12 al 19/4 (sota disponibilitat). Nens de 0 a 5 anys: s\'allotgen de franc. Xiquets de 0 a 11 anys: el 1r viatja gratis i el 2n amb un 50% de descompte.', '85.00', 0, '2024-12-24 19:43:00', 'AD', 'panoramica5 (3).jpg'),
(45, 'Relaxa\'t en un hotel 4* de conte al nord de Portugal', '2 días y 1 noche en el Ribeira Collection Hotel 4* ubicado en Arcos De Valdevez (al norte de Portugal), con desayunos + 1 acceso diario al circuito termal SPA Health Club (piscina, jacuzzi y sauna).', '39.00', 0, '2024-12-26 19:44:00', 'PT', 'panoramica5 (4).jpg'),
(53, 'Egipte: hotel 4*, vols, excursions exclusives i creuer pel riu Nil', 'Sortides des de MADRID, BILBAO i BARCELONA.\r\nInclou: vol d\'anada a Luxor i tornada des del Caire + trasllats + 4 nits de creuer Grand Princess o similar a Pensió Completa + 3 nits al Caire a hotel 4* amb esmorzars + visites durant el creuer + guia de parla hispana + taxes + maleta facturada + assegurança bàsica de viatge.', '549.00', 0, '2025-03-17 20:39:00', 'EG', 'panoramica5 (8).jpg'),
(54, 'Roma t\'enamorarà: hotel 3* amb esmorzars', '3 dies i 2 nits a l\'Hotel San Giusto 3* situat a 7 km del centre de Roma, amb esmorzars.', '58.00', 0, '2025-01-17 22:43:00', 'IT', 'panoramica5.jpg'),
(55, 'Setmana Santa i més a Sardenya (amb allotjament i vaixell inclosos)', '8 nits (1 nit navegació + 7 nits als apartaments) + anada amb vaixell des de Barcelona en cabina interior i tornada en passatge bàsic amb la companyia Grimaldi Lines, en apartament amb 1 dormitori dels Apartaments Badus ubicats a Badesi, entre Castelsardo i Santa Teresa di Gallura + taxes d\'embarcament incloses + embarca el teu cotxe o moto gratis al vaixell. El preu està calculat amb una ocupació de 4 persones a l\'apartament, si en sou 2, podeu viatjar des de 183 €/pers.', '299.00', 0, '2025-01-01 22:46:00', 'IT', 'panoramica5 (1).jpg'),
(56, 'Hotel 4* amb piscina interior al bell mig de la natura del Montseny', '2 dies i 1 nit al Senator Montanyà Hotel & Lodge 4* situat a Seva (Montseny) amb esmorzar + accés a la piscina interior + 2x1 a l\'spa per persona i reserva (vàlid per a tots els dies excepte els dissabtes). L\'hotel és a menys d\'una hora de Barcelona!', '50.00', 0, '2025-01-31 23:59:00', 'ES', 'panoramica5 (2).jpg'),
(57, 'Setmana Santa a Tenerife amb vols inclosos!', 'Sortides des de Madrid.\r\n5 nits a Hotel Parque Vacacional Edén 3*, ubicat a Puerto de la Cruz, amb mitja pensió + vols d\'anada i tornada + assegurança bàsica de viatge. També disponible a Pensió completa des de 339€.', '299.00', 0, '2025-08-31 22:50:00', 'ES', 'panoramica5 (3).jpg'),
(58, 'Gaudeix de 2 dies a Disneyland®! Inclou vols i hotel 3*', 'Sortides des de MADRID i BARCELONA!\r\n3 nits en hotels 3* a confirmar a la zona Torcy a Solo Allotjament + vols d\'anada i tornada + 2 entrades d\'1 dia per persona als parcs de Disneyland Paris. També disponible en hotels 3* a la zona Disney des de 449€.', '429.00', 0, '2025-02-15 17:53:00', 'FR', 'panoramica5 (4).jpg'),
(59, '¡París amb vols, entrada a l\'Arc del Triomf i creuer!', 'Sortides des de MADRID i BARCELONA de GENER a MARÇ.\r\n3 nits a París allotjats a l\'hotel 3* + vols d\'anada i tornada + tour gratuït + creuer pel riu Sena + entrada a l\'Arc del Triomf o pujada a la Torre Eiffel. També disponible en règim d\'Allotjament i Esmorzar des de 239€!', '218.00', 0, '2025-04-17 22:58:00', 'FR', 'paris-francia-05.jpg'),
(60, 'Cap d\'any a Santa Susana amb sopar de gala i festa a Hotel 4*', '2 dies i 1 nit a l\'Hotel Alegria Florida Park 4* situat a Santa Susanna (Costa Maresme) amb Festa de Cap d\'Any: sopar de gala, raïm de la sort, cotilló, música DJ amb barra lliure i brunch d\'any nou de 10-15h.\r\n\r\n Nens de 2 a 11 anys: 1r i 2n viatgen amb un 50% de descompte', '229.00', 0, '2024-12-31 23:00:00', 'ES', 'panoramica5 (5).jpg'),
(61, 'Sri Lanka al complet amb vols inclosos!', 'Sortides disponibles al desembre, abril, juliol i agost.\r\n10 nits (1 en vol): Vols anada i tornada des de Madrid a Colombo amb escala a Istanbul + 2 nits a Sigiriya + 2 nits a Kandy + 2 nits a Nuwara Eliya + 1 nit a Yala + 2 nits a Bentota a Mitja Pensió + entrades per a les visites amb guia de parla hispana + trasllats + assegurança bàsica de viatge.', '1839.00', 0, '2025-02-12 23:04:00', 'LK', '31140-sri-lanka-al-completo-con-vuelos-incluidos-13.jpeg');